name: CI/CD Pipeline

on:
  push:
    branches: ['main', 'dev', 'stage']
  pull_request:
    branches: ['main', 'dev', 'stage']

jobs:
  build:
    name: Build e Testes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest pytest-cov bandit pip-audit
      - name: Run unit tests
        run: pytest
      - name: Bandit Security Scan
        run: bandit -r . -x tests
      - name: Dependency Audit
        run: pip-audit --ignore-vuln GHSA-w8qv-h299-4p8h # Exemplo de como ignorar falso positivo se necessário

  deploy_and_scan_stage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t task-manager-app .
      - name: Run Container
        run: docker run -d -p 5000:5000 --name meu-app-stage task-manager-app
      - name: OWASP ZAP Baseline Scan
        run: |
          sleep 15
          docker run --rm -v $(pwd):/zap/wrk/:rw -t zaproxy/zap-stable zap-baseline.py -t http://$(hostname -I | awk '{print $1}'):5000 || true
